version: '2.1'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    env_file:
    - .env
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL= #enter URL
      - DUCKDNSTOKEN= # enter DUCKDNS token
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - EMAIL= # enter Email
      - DHLEVEL=2046
    volumes:
      - ./letsencrypt/:/config # set where you want to mount your volume
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
  duckdns:
    env_file:
    - .env
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Berlin
      - SUBDOMAINS=stahldom
      - TOKEN= #set Token
      - LOG_FILE=true #optional
    volumes:
      - ./duckdns/:/config #optional
    restart: unless-stopped
  code-server:
    env_file:
    - .env
    privileged: true
    build: .
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD= #update with secure password
      - SUDO_PASSWORD= #update with secure password
    volumes:
      - ./code-server/:/config #set where you want to mount your workspace
    restart: unless-stopped

